language: node_js
install:
  - yarn
node_js:
  - "12"
  - "10"
  - "14"
addons:
  chrome: stable
sudo: required
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"